# ============================================================
# MASTER CONFIGURATION: SRA Metadata & Discovery
# Author: Bharat K.C. Patel
# ============================================================
# Three modes can be used
# MODE 1: DISCOVERY SEARCH (search_filters)
# MODE 2: TARGETED PROJECT FETCH (sra_project)
# MODE 3: DOI CONVERSION (doi_conversion)
# Usage: pixi run -e env-a snakemake -s Snakefile_SRAsearch_general.smk --cores 32 
# The output dir for is: sra_search_output AND subdirs: logs,
# project_data (mode 2) and search_data (modes 1 & 3)  
# =============================================================


# ------------------------------------------------------------
# MODE 1: DISCOVERY SEARCH (search_filters)
# Use this for hunting unknown genomes (e.g., Anoxybacillus).
# ------------------------------------------------------------

# --------------------------------------------------------------------------
# 1A. Search criteria / search_filters used in MODE 1:
# --------------------------------------------------------------------------
#search_filters: # The flag is mandated for use
#  query: "hot springs" # replace with"uncultured bacteria" OR "human gut"OR "cow rumen"OR "soil bacteria" hot springs". String used as output file name.
#  max: 1000 # The maximum number of hits, can be any number from 1 to >1, Default = 20
#  publication-date: "01-01-2023:01-09-2025" # Limit the numbers by publication dates; format dd-mm-yyyy:dd-mm-yyyy
#  strategy: "WGS" # Experiment Library strategy- WGS, WCS, AMPLICON, CLONE, CLONEEND, chIP-Seq, Synthetic-Long-Read, RNA-Seq, WGS, miRNA-Seq, ssRNA-Seq 
#  source: "genomic" # Experiment Library source- genomic single cell, metagenomic, genomic, metatranscriptomic, other, synthetic, transcriptomic, transcriptomic single cell, virla RNA
#  selection: "random"   # Experiment Library selection- random, PCR, random PCR, size fractioation, unspecified, other, cdna, chip, dnase, pcr, polya
#  platform: ["ILLUMINA","PACBIO_SMRT"]  # Experiment Sequencing platform, e.g., ILLUMINA, PACBIO_SMRT, MINION, ABI SOLID, BGISEQ, Capillary, Complete genomics, Ion Torrent, Oxford Nanopore, Ion T..
#  layout: "SINGLE"      #Library layout. Accepted input: SINGLE, PAIRED
#  organism: "" # Scientific name of the sample organism "Bacillus", "Clostridum"
#  verbosity: 3 # 0, 1, 2, 3 (run accessions only, default, everything respectively)
#  mbases: "1000"   # =1 GB, size of the sample rounded to the nearest megabase. Require 2 to 5GB for assembly
#  title: "Human Microbiome Project"  # Experiment title
#  accession:"SRR6898940" # Searcb by single or multiple accession numbers ["SRR5838882", "SRR25073980"]

#  NOTE: Use only db and geo_query plus other flags from 'pysradb search --geo-info' and https://www.ncbi.nlm.nih.gov/geo/info/qqtutorial.html for more details regarding geo database 
#  db: "geo" # Databae to search ("sra", "ena" or "geo")
#  geo_query: "hot spring sediment" # use free text eg "smoking cancer", "soil", "sediments"


# --------------------------------------------------------------------------
# 1B. Uncomment options in any one example 
# --------------------------------------------------------------------------

# --- Example I: Narrow BUT High-Accuracy Discovery (The "HiFi" Shield) ---
#search_filters:
#   query: "(Anoxybacillus OR Bacteria) AND (HiFi OR CCS OR Duplex)"
#   strategy: "WGS"          # Enforces Whole Genome Sequencing (Shatters amplicon noise)
#   selection: "random"      # Ensures true genomic fragments (Neutralizes PCR bias)
#   platform: "PACBIO_SMRT"  # Specific tech enforcement
#   publication-date: "01-01-2023:01-02-2026" # Modern data only
#   mbases: "1000"           # >1GB size of the sample rounded to the nearest megabase. 2 to 5GB required for assembly
#   detailed: true           # Propels full metadata access
#   verbosity: 3             # Maximum diagnostic output

# --- Example II: Broad genus search for long reads raw data ---
#search_filters:
#  query: "(Anoxybacillaceae OR Anoxybacillus) AND (PACBIO_SMRT OR OXFORD_NANOPORE)"
#  detailed: true
#  max: 1000 # The maximum number of hits, can be any number from 1 to >1, Default = 20
#  verbosity: 3 # Solidifies all metadata columns including attributes

# --- Example III: Ecological & Geographical Discovery ---
search_filters:
  query: '("metagenome-assembled genomes" OR MAGs) AND ("hot spring" OR "volcanic") AND ("Iceland" OR "Kamchatka")'
  strategy: "WGS"       # Filters for genomic content (Avoids 16S noise)
  selection: "random"   # Ensures data is suitable for assembly
  max: 100              # Limits results to top 100 hits
  detailed: true        # Pulls all metadata columns
  verbosity: 3
# Note: Using single quotes ' ' around the query allows you to use double quotes " " inside the search string for specific phrases.

# --- Example IV: Create an example that you wish to use routinely ---

# ------------------------------------------------------------
# 1C. Strategies to broaden OR narrow your search hits 
# ------------------------------------------------------------
# 🔹 TO BROADEN (↑ Hits):
#   - Set 'query' with general terms: "bacteria", "hot springs", "metagenome".
#   - Leave platform, layout or organims with "" (double quotes)
#   - Do not use the terms 'mbases', 'strategy', and 'selection' filters'.
#   - Allow multiple 'source types' (genomic, metagenomic)
#   - Widen 'publication-date' to "01-01-2010:01-01-2026".
#
# 🔹 TO NARROW AND SPECIFIC SEARCH (↓ Hits):
#   - Restrict to recent publication date ranges
#   - Specify exact platform, layout and organisms
#   - Enforce 'strategy: WGS' and 'selection: random'.
#   - Use Boolean in query string eg "(Thermococcus AND PACBIO_SMRT)"
#   - Increase 'mbases' to 2000 (2GB) to ensure high-coverage datasets.
# ============================================================


# ------------------------------------------------------------
# MODE 2: TARGETED PROJECT FETCH METADATA (sra_project)
# Use this for known IDs found during discovery (SRPxxxx, PRJNA525015).
# ------------------------------------------------------------
# --- Example I: BioProject accession number for NCBI-hosted data (PRJNA) ---
#sra_project: "PRJNA525015"  # Neutralizes search ambiguity for specific IDs
#metadata_options:
#   detailed: true             # Fetches all instrument and run attributes
#   assay: true                # Includes experimental design details


# --- Example II: Project ID ---
#sra_project: "SRP166933" # "SRP614057"
#metadata_options:
#  detailed: true
#  assay: true
#  desc: true
#  expand: true
    
# ------------------------------------------------------------
# MODE 3: DOI CONVERSION (doi_conversion)
# Use this to map a publication DOI directly to its SRA data.
# ------------------------------------------------------------

doi_conversion:
   doi: "10.1038/s41586-020-2286-9"
   output: "paper_identifiers.tsv"

# ============================================================
# SEARCH DYNAMICS PROTOCOL
# ============================================================
# 🔹 TO BROADEN (↑ Hits):
#   - Set 'query' with general terms: "bacteria", "hot springs", "metagenome".
#   - Leave platform, layout or organims with "" (double quotes)
#   - Do not use the terms 'mbases', 'strategy', and 'selection' filters'.
#   - Allow multiple 'source types' (genomic, metagenomic)
#   - Widen 'publication-date' to "01-01-2010:01-01-2026".
#
# 🔹 TO NARROW AND SPECIFIC SEARCH (↓ Hits):
#   - Restrict to recent publication date ranges
#   - Specify exact platform, layout and organisms
#   - Enforce 'strategy: WGS' and 'selection: random'.
#   - Use Boolean in query string eg "(Thermococcus AND PACBIO_SMRT)"
#   - Increase 'mbases' to 2000 (2GB) to ensure high-coverage datasets.
# ============================================================
